# Generated by Django 6.0.5 on 2026-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('length', models.FloatField(help_text='Length in cm or inches')),
                ('width', models.FloatField(help_text='Width in cm or inches')),
                ('thickness', models.FloatField(help_text='Thickness in cm or inches')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order', models.IntegerField(default=1)),
                ('delivery_time', models.CharField(help_text='e.g., 7-14 business days', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Any other important details', null=True)),
            ],
        ),
    ]
